[package]
name = "jsdotlua/expect"
version = "3.6.1-rc.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
"jest-get-type" = "jsdotlua/jest-get-type@3.6.1-rc.2"
"jest-matcher-utils" = "jsdotlua/jest-matcher-utils@3.6.1-rc.2"
"jest-message-util" = "jsdotlua/jest-message-util@3.6.1-rc.2"
"jest-roblox-shared" = "jsdotlua/jest-roblox-shared@3.6.1-rc.2"
"jest-snapshot" = "jsdotlua/jest-snapshot@3.6.1-rc.2"
"jest-util" = "jsdotlua/jest-util@3.6.1-rc.2"
"luau-polyfill" = "jsdotlua/luau-polyfill@^1.2.6"
promise = "jsdotlua/promise@^3.5.0"
"luau-regexp" = "jsdotlua/luau-regexp@^0.2.1"
