[package]
name = "jsdotlua/jest-message-util"
version = "3.6.1-rc.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
chalk = "jsdotlua/chalk@^0.2.1"
"jest-roblox-shared" = "jsdotlua/jest-roblox-shared@3.6.1-rc.2"
"jest-types" = "jsdotlua/jest-types@3.6.1-rc.2"
"luau-polyfill" = "jsdotlua/luau-polyfill@^1.2.6"
"pretty-format" = "jsdotlua/pretty-format@3.6.1-rc.2"
"luau-regexp" = "jsdotlua/luau-regexp@^0.2.1"
