[package]
name = "jsdotlua/jest-test-result"
version = "3.6.1-rc.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
"jest-types" = "jsdotlua/jest-types@3.6.1-rc.2"
"luau-polyfill" = "jsdotlua/luau-polyfill@^1.2.6"
