[package]
name = "jsdotlua/jest-roblox-shared"
version = "3.6.1-rc.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
"jest-get-type" = "jsdotlua/jest-get-type@3.6.1-rc.2"
"jest-mock" = "jsdotlua/jest-mock@3.6.1-rc.2"
"luau-polyfill" = "jsdotlua/luau-polyfill@^1.2.6"
