[package]
name = "jsdotlua/path"
version = "3.6.1-rc.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
"luau-polyfill" = "jsdotlua/luau-polyfill@^1.2.6"
