[package]
name = "jsdotlua/jest-core"
version = "3.6.1-rc.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
chalk = "jsdotlua/chalk@^0.2.1"
emittery = "jsdotlua/emittery@3.6.1-rc.2"
"jest-config" = "jsdotlua/jest-config@3.6.1-rc.2"
"jest-console" = "jsdotlua/jest-console@3.6.1-rc.2"
"jest-message-util" = "jsdotlua/jest-message-util@3.6.1-rc.2"
"jest-reporters" = "jsdotlua/jest-reporters@3.6.1-rc.2"
"jest-roblox-shared" = "jsdotlua/jest-roblox-shared@3.6.1-rc.2"
"jest-runner" = "jsdotlua/jest-runner@3.6.1-rc.2"
"jest-runtime" = "jsdotlua/jest-runtime@3.6.1-rc.2"
"jest-snapshot" = "jsdotlua/jest-snapshot@3.6.1-rc.2"
"jest-test-result" = "jsdotlua/jest-test-result@3.6.1-rc.2"
"jest-types" = "jsdotlua/jest-types@3.6.1-rc.2"
"jest-util" = "jsdotlua/jest-util@3.6.1-rc.2"
"luau-polyfill" = "jsdotlua/luau-polyfill@^1.2.6"
"pretty-format" = "jsdotlua/pretty-format@3.6.1-rc.2"
promise = "jsdotlua/promise@^3.5.0"
"luau-regexp" = "jsdotlua/luau-regexp@^0.2.1"
